# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Development

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Release Development Linux"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
    
      - name: Install dependencies
        run: flutter packages get     

      - name: Download Artifact Wallet Build
        run: |
          
          mkdir -p ./assets
          mkdir -p ./assets/wallet
          
          cd ./assets/wallet

          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip > wallet-build.zip
          unzip wallet-build.zip
          rm wallet-build.zip
          
          cd ../../

      # run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

      - name: Upload android artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-android
          path: |
            ./build/app/outputs/apk/release/app*
            ./build/app/outputs/bundle/release/app*
          retention-days: 3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/**
