# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Development

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  pre-release-ios:
    name: "Release Development iOS"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter packages get

      - name: Download Artifact Wallet Build
        run: |

          mkdir -p ./assets
          mkdir -p ./assets/wallet

          cd ./assets/wallet

          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip > wallet-build.zip
          unzip wallet-build.zip
          rm wallet-build.zip

          cd ../../

      # run: flutter test
      - run: flutter build ipa --release --no-codesign
      - run: flutter build ios --release --no-codesign

      - run: |        
          (cd ./build/ios/iphoneos/; zip -r Runner.app.zip Runner.app)
          (cd ./build/ios/archive/; zip -r Runner.xcarchive.zip Runner.xcarchive)

      - name: Upload ios artifacts1
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-ios1
          #path: ./build/ios/archive/*.xcarchive
          path: ./build/ios/archive/Runner.xcarchive.zip
          retention-days: 3

      - name: Upload ios artifacts2
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-ios2
          #path: ./build/ios/**.ipa
          path: ./build/ios/iphoneos/Runner.app.zip
          retention-days: 3


  pre-release-android:
    name: "Release Development Android"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
    
      - name: Install dependencies
        run: flutter packages get     

      - name: Download Artifact Wallet Build
        run: |
          
          mkdir -p ./assets
          mkdir -p ./assets/wallet
          
          cd ./assets/wallet

          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip > wallet-build.zip
          unzip wallet-build.zip
          rm wallet-build.zip
          
          cd ../../

      # run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

      - name: Upload android artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-android
          path: |
            ./build/app/outputs/apk/release/app*
            ./build/app/outputs/bundle/release/app*
          retention-days: 3


  pre-release-upload:
    name: "Upload release"
    needs: [ pre-release-android, pre-release-ios ]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout wallet
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin/artifacts

      - name: Display structure of artifacts
        run: ls -R
        working-directory: bin/artifacts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development"
          prerelease: true
          title: "Development Build"
          files: |
            ./bin/artifacts/**